### ISSUE TITLE
No proxy in TBLPROPERTIES

### ISSUE THREAD

**Issue by tsystemsbigdata** [lucidworks/hive-solr#2]
assuming that the SerDe uses somethimg similar to 

curl "http://destinationserver.domain:port/solr/core/update?commit=true"

to insert the Hive data into Solr, the following is needed in my case: 

TBLPROPERTIES
(
'solr.server.proxycommand' = '--noproxy destinationserver.domain'
)

resulting in:
curl "http://destinationserver.domain:port/solr/core/update?commit=true" --noproxy destinationserver.domain

**Comment by acesar** [comment]
The SerDe uses SolrJ (which uses Apache Http client under the covers).

Can you elaborate on the issue, what are trying to address?

**Comment by tsystemsbigdata** [comment]
Hi,

I am trying to insert Data from Hive into Solr using the SerDe.

In my current Project the Solr server is located outside the cluster, and to reach it with e.g. curl or similar http requests it is required to provide the “--noproxy solrservername.domain” switch


[cid:image004.png@01D16FA5.07B2CB60]

I can insert Data into Solr from the Hadoop Cluster using curl, but when I try with the SerDe in Hive I get this error

at org.apache.hadoop.hive.ql.exec.mr.ExecReducer.reduce(ExecReducer.java:265)
                at org.apache.hadoop.mapred.ReduceTask.runOldReducer(ReduceTask.java:444)
                at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:392)
                at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
                at java.security.AccessController.doPrivileged(Native Method)
                at javax.security.auth.Subject.doAs(Subject.java:415)
                at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
                at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row

at org.apache.hadoop.hive.ql.exec.mr.ExecReducer.reduce(ExecReducer.java:253)
                ... 7 more
Caused by: java.lang.NullPointerException
                at com.lucidworks.hadoop.io.impl.LWSolrDocument.getId(LWSolrDocument.java:59)
                at com.lucidworks.hadoop.io.LucidWorksWriter.write(LucidWorksWriter.java:187)
                at com.lucidworks.hadoop.hive.LWHiveOutputFormat$1.write(LWHiveOutputFormat.java:39)
                at org.apache.hadoop.hive.ql.exec.FileSinkOperator.processOp(FileSinkOperator.java:689)
                at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:815)
                at org.apache.hadoop.hive.ql.exec.SelectOperator.processOp(SelectOperator.java:84)
                at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:815)
                at org.apache.hadoop.hive.ql.exec.LimitOperator.processOp(LimitOperator.java:51)
                at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:815)
                at org.apache.hadoop.hive.ql.exec.SelectOperator.processOp(SelectOperator.java:84)
                at org.apache.hadoop.hive.ql.exec.mr.ExecReducer.reduce(ExecReducer.java:244)
                ... 7 more

I have tested my code in a Virtual Machine and it works perfect.

Thanks for your interest!

**Comment by acesar** [comment]
The exception seems unrelated to the `--noproxy` request.

Please, checkout the latest source code and use Solr cloud instead. You will need to provide the zookeeper string.
```
TBLPROPERTIES(
     'solr.zkhost' = 'zknode1:2181,zknode2:2181,zknode3:2181/solr', 
       ...
)
```

**Comment by tsystemsbigdata** [comment]
So this means that only Solr cloud with zookeeper is supported ?
