### ISSUE TITLE
Not being able to insert data in external Hive table connected to Solr

### ISSUE THREAD

**Issue by Oswfrans** [lucidworks/hive-solr#25]
Hi all,

Hive Version 1.2.1000
Solr Version 5.5.2.2.5
Hadoop Version 2.5.3.0
solr-hive-serde-3.0.0.jar

I wanted to implement an external hive table connected to solr.

I built the JAR file on my local pc and uploaded it to HDFS. After that I connected to our cluster using putty, then connected to Hive using Beeline.

After being successfully connected I loaded the jar file

    add jar hdfs:///user/hbx/solr-hive-serde-3.0.0.jar;

Then I create an empty external table following the example from the documentation:

    CREATE EXTERNAL TABLE solr_test (city STRING, edition INT, sport STRING, 
    sub_sport STRING, athlete STRING, country STRING, gender STRING, event 
    STRING, event_gender STRING, medal STRING) STORED BY 
    'com.lucidworks.hadoop.hive.LWStorageHandler' LOCATION '/tmp/solr' 
    TBLPROPERTIES('solr.server.url' = 'https://hdpmst003.example.hbx:8080/', 
    'solr.collection' = 'collection1', 'solr.query' = '*:*', 'lww.jaas.file' = 
    '/etc/solr/conf/solr-server-jaas.conf');

I ensured that lww.jaas.file is present in the same location on all active nodes per the following doc: 
>"The JAAS configuration file must be copied to the same path on every node where a Node Manager is running (i.e., every node where map/reduce tasks are executed)" 

After creating the table without data and without error messages I try to insert data from another table into this table. Here the code breaks down and we get various error messages.

The errors start during the mapping tasks, the start reads:
    
    0: jdbc:hive2://hdpmst001.example.hbx:8080> INSERT OVERWRITE TABLE solr_test 
    SELECT * FROM solr_olympics; 
    INFO : Session is already open 
    INFO : Dag name: INSERT OVERWRITE TABLE solr_...solr_olympics(Stage-1) 
    INFO : 

    INFO : Status: Running (Executing on YARN cluster with App id 
    application_1492773261214_8070) 

    INFO : Map 1: -/- 
    INFO : Map 1: 0/1 
    INFO : Map 1: 0(+1)/1 
    INFO : Map 1: 0(+1,-1)/1 
    INFO : Map 1: 0(+1,-1)/1 
    INFO : Map 1: 0(+1,-2)/1 
    INFO : Map 1: 0(+1,-3)/1 
    INFO : Map 1: 0(+1,-3)/1 
    INFO : Map 1: 0(+1,-3)/1 
    ERROR : Status: Failed 
    ERROR : Vertex failed, vertexName=Map 1, 
   
    vertexId=vertex_1492773261214_8070_5_00, diagnostics=[Task failed, 
    taskId=task_1492773261214_8070_5_00_000000, diagnostics=[TaskAttempt 0 
    failed, info=[Error: Failure while running task:java.lang.RuntimeException: 
    java.lang.RuntimeException: 
    org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while 
    processing row 

The end of the error message reads:

    Caused by: java.lang.NullPointerException 
    at com.lucidworks.hadoop.io.impl.LWSolrDocument.getId(LWSolrDocument.java:46) 
    at com.lucidworks.hadoop.io.LucidWorksWriter.write(LucidWorksWriter.java:195) 
    ... 27 more 
    ]], Vertex did not succeed due to OWN_TASK_FAILURE, failedTasks:1 killedTasks:0, Vertex vertex_1492773261214_8070_6_00 [Map 1] killed/failed due to:OWN_TASK_FAILURE]DAG did not succeed due to VERTEX_FAILURE. failedVertices:1 killedVertices:0 (state=08S01,code=2) 

Any help in finding a thread to pull on would be greatly appreciated.

**Comment by acesar** [comment]
The table must have an `id`.

Try with:
```
CREATE EXTERNAL TABLE solr_test (id STRING, ...
```

**Comment by Oswfrans** [comment]
Hi acesar, thank you for your reply. I amended my creation of the table to
    solr_test (ID INT, name STRING) 
Now I get a new error, start of the error:
    ERROR : Vertex failed, vertexName=Map 1, vertexId=vertex_1492773261214_14661_4_00, diagnostics=
    [Task failed, taskId=task_1492773261214_14661_4_00_000000, diagnostics=[TaskAttempt 0 failed, 
    info=[Error: Failure while running task:java.lang.RuntimeException: java.lang.RuntimeException: Hive 
    Runtime Error while closing operators
    at org.apache.hadoop.hive.ql.exec.tez.TezProcessor.initializeAndRunProcessor(TezProcessor.java:173)
    at org.apache.hadoop.hive.ql.exec.tez.TezProcessor.run(TezProcessor.java:139)
    at 
    org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.run(LogicalIOProcessorRuntimeTask.java:347)

End of the error:
Caused by: java.io.IOException
        at com.lucidworks.hadoop.io.LucidWorksWriter.makeIOException(LucidWorksWriter.java:287)
        at com.lucidworks.hadoop.io.LucidWorksWriter.close(LucidWorksWriter.java:282)
        at com.lucidworks.hadoop.hive.LWHiveOutputFormat$1.close(LWHiveOutputFormat.java:50)
        at org.apache.hadoop.hive.ql.exec.FileSinkOperator$FSPaths.closeWriters(FileSinkOperator.java:199)
        ... 21 more
Caused by: shaded.org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at https://hdpmst003.adam.payvision:8983/collection1: Expected mime type application/octet-stream but got text/html. <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 404 </title>
</head>
<body>
<h2>HTTP ERROR: 404</h2>
<p>Problem accessing /collection1/update. Reason:
<pre>    Not Found</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>

        at shaded.org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:578)
        at shaded.org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:279)
        at shaded.org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:268)
        at shaded.org.apache.solr.client.solrj.impl.ConcurrentUpdateSolrClient.request(ConcurrentUpdateSolrClient.java:436)
        at shaded.org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:160)
        at shaded.org.apache.solr.client.solrj.SolrClient.commit(SolrClient.java:484)
        at shaded.org.apache.solr.client.solrj.SolrClient.commit(SolrClient.java:501)
        at com.lucidworks.hadoop.io.LucidWorksWriter.close(LucidWorksWriter.java:278)
        ... 23 more

Any further suggestion would be greatly appreciated.

**Comment by acesar** [comment]
@Oswfrans the Solr url does not seem correct: 

```
TBLPROPERTIES('solr.server.url' = 'https://hdpmst003.example.hbx:8080/', 
```

Usually is in the format `http://<hostname>:8983/solr`

If you are using SolrCloud please use the `solr.zkhost` instead
